### ISSUE TITLE
classymenu.py with once show

### ISSUE THREAD

**Issue by MarkusHackspacher** [Lysander/snippets#5]
I have use your classymenu.py in
https://github.com/MarkusHackspacher/pycupbetting

And add a function, show a menu one time for a selection.

```
    def run(self, once=False):
        """
        Core method to handle a menu. This invokes a loop that handles all
        menu tasks as long as the main menu is exited by the user.
        """
        menushow = True
        while menushow:
            if once:
                menushow = False
```

**Comment by Lysander** [comment]
Hi,

sorry for my late answer, but I just saw your comment!

Nice to see, that you could use my proposal :-)

To be honest, I would prefer another solution than a "magically" parameter. Perhaps one can provide two calls, one for a single menu-action and one for the "run forever"-mode. I prefer clearly named features over endless parameters that change the flow of a function. Internally one can of course use a parameter, but perhaps that would be obsolete...

Thank you for your idea - perhaps I will think about it further more an improve it :-)

**Comment by MarkusHackspacher** [comment]
Another reason to use a parameter, is I can close a submenu to return to main, I set only submenu.menushow = False.
In my example I delete a datatable and the progamm return to main menu.

```
def delete_cup_winner_bet():
    session.delete(cup_winner_bet)
    cup_winner_betselect.menushow = False
    return
```

**Comment by Lysander** [comment]
Ok, I thought about it and think it is a good idea. I just made a change and added your proposal to my implementation.But I simplified the code a bit 😉
